language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t anil/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true anil/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "docker-react-env"
  bucket_name: elasticbeanstalk-us-east-1-738084010856
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"